global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nodes"
    static_configs:
      - targets:
          - "10.194.70.10:9100"
          - "10.194.70.20:9100"
          - "10.194.70.30:9100"

  - job_name: "rms_inference"
    metrics_path: /metrics
    static_configs:
      - targets: ["137.194.194.122:8000"]
        labels:
          node: "rms"
          service: "inference"

  - job_name: "aura_router"
    static_configs:
      - targets: ["137.194.194.21:9000"]

  - job_name: "gpu_inference"
    metrics_path: /metrics
    static_configs:
      - targets: ["172.17.0.1:18000"]
        labels:
          node: "gpu"
          service: "inference"
